print("Welcome to Credit Card Application Simulator!")
age = int(input("please enter age here... "))
elif age == 0: input("YOU HAVENT BEEN BORN YET!! GET BORN!")
if age <<18: input("YOU ARENT ABLE TO GET A CREDIT CARD BUCKO GOODBYE PRESS ENTER TO LEAVE")
elif age >=18: print(q1)
q1 = input("alright, now WHATS NINE PLUS TEN????")

if q1 == 21: print("THIS IS A CREDIT CARD APPLICATION NOT A MEME")
elif q1 == 19:print(q2)
  q2 = input("ok now a better question, HWO MADE THIS??? Qwertz Studio, Thermonuclear, Orange the Wiz, or ted d fegs")
if q2 == "Thermonuclear": input("nope thermonuclear has a different studio")
elif q2 == "ted d fegs": input("bro ted d fegs isnt even real 90% of the time")
elif q2 == "Orange the Wiz": input("nope he does javascript these days")
elif q2 == "Qwertz Studio": print(q3)
q3 = input("LAST QUESTION!!! where do you live? your house, my basement, or, with your parents")

if q3 == "your house": input("THATS CORRECT YOU GET A CREDIT CARD")
elif q3 == "or": input("WHAT DO YOU MEAN 'OR'???????????????????")
elif q3 == "my basement": input("get out")
elif q3 == "with your parents": input("reasonable answer, credit card is yours i guess")
